FROM            mubiic/ubuntubare:14.04.2
MAINTAINER      Howard Mei      <howardmei@mubiic.com>


ENV             DEBIAN_FRONTEND noninteractive
# Add bash profile for interactive terminal
COPY            root            /root

# Creat additonal binary path and set proper permissions
RUN             mkdir -p /opt/bin /opt/sbin /opt/shbin && \
                chmod -R 0755 /opt/bin /opt/sbin /opt/shbin

ENV             PATH            /opt/bin:/opt/sbin:/opt/shbin:$PATH

# Update bash, coreutils and install Curl and add HTTPS support to APT
RUN             apt-get-min update && apt-install-min bash coreutils curl ca-certificates apt-transport-https && \
                apt-cleanup-min && unset DEBIAN_FRONTEND && env --unset=DEBIAN_FRONTEND

# Set Default User and Wordking Dir
USER            root
ENV             HOME            /root
WORKDIR         /root

# Define base volume as a common attach point.
VOLUME          ["/opt/shbin"]

# Define default command as the entry point.
CMD             ["/bin/bash"]
