FROM            mubiic/ubuntubash:14.04.2
MAINTAINER      Howard Mei      <howardmei@mubiic.com>
ENV             TIMEZONE        Asia/Singapore
# LANGPACK is tricky, e.g. zh-hans vs zh-hant etc
ENV             LANGPACK        en
ENV             LOCALE          en_US.UTF-8
ENV             KUBECONF        **TBD**
ENV             APPCONF         **TBD**


ENV             DEBIAN_FRONTEND noninteractive
# Update the timezone and locale according to the env variables set above
RUN             apt-get-min remove language-pack* && apt-get-min update && \
                apt-install-min htop procps locales tzdata language-pack-${LANGPACK} \
                language-pack-${LANGPACK}-base && echo $TIMEZONE > /etc/timezone && \
                cp -f /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
                dpkg-reconfigure -f noninteractive tzdata && date \
                locale-gen en_US.UTF-8 $LOCALE && update-locale LANG=$LOCALE LC_CTYPE=$LOCALE && \
                apt-get-min remove tzdata && apt-get-min autoremove -yq && apt-cleanup-min

ENV             LANG            $LOCALE
ENV             LANGUAGE        $LOCALE
ENV             LC_ALL          $LOCALE

# Add s6suite overlay to provide init manager
ADD             https://github.com/just-containers/s6-overlay/releases/download/v1.9.1.3/s6-overlay-amd64.tar.gz /tmp/s6-overlay.tar.gz
RUN             tar xvfz /tmp/s6-overlay.tar.gz -C / && rm -f /tmp/s6-overlay.tar.gz


# Create a devops user in sudo group and initialize its home directory
# Remember to use gosu devops:sudo to run daemon processes because sudo is removed here
RUN             adduser --system --shell /bin/bash --gecos 'DevOps User in Sudo Group' \
                --ingroup sudo --disabled-password --home /home/devops devops && \
                cp -f /root/.bashrc /root/.bash_profile /root/.bash_prompt /root/.inputrc \
                      /root/.gitconfig /root/.gitignore /root/.gitattributes /home/devops && \
                chown -R devops:sudo /home/devops && \
                mkdir -p /opt/app && touch /opt/app/.placeholder && chown -R devops:sudo /opt/app && \
                unset DEBIAN_FRONTEND && env --unset=DEBIAN_FRONTEND

# Set Default User and Wordking Dir
USER            devops
ENV             HOME            /home/devops
WORKDIR         /opt/app

# Define base volume as a common attach point.
VOLUME          ["/opt/app"]

ENTRYPOINT ["/init"]
CMD []
